# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget {\n"
"    border: 1px solid gray;   /* 边框 */\n"
"    border-radius: 2px;   /* 圆角 */\n"
"}\n"
"\n"
"QToolButton{\n"
"    border: 1px solid gray;   /* 边框 */\n"
"    border-radius: 2px;   /* 圆角 */\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    border: 1px solid gray;   /* 边框 */\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 2px;   /* 圆角 */\n"
"}\n"
"QComboBox{\n"
"    border: 1px solid gray;   /* 边框 */\n"
"    border-radius: 3px;   /* 圆角 */\n"
"}\n"
"QToolTip{\n"
"    font: 10pt \"JetBrains Mono\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wifiBox = QtWidgets.QComboBox(self.centralwidget)
        self.wifiBox.setObjectName("wifiBox")
        self.horizontalLayout.addWidget(self.wifiBox)
        self.ipLabel = QtWidgets.QLabel(self.centralwidget)
        self.ipLabel.setObjectName("ipLabel")
        self.horizontalLayout.addWidget(self.ipLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.tempLabel = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel.setMinimumSize(QtCore.QSize(50, 20))
        self.tempLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.tempLabel.setText("")
        self.tempLabel.setObjectName("tempLabel")
        self.horizontalLayout.addWidget(self.tempLabel)
        self.tempBar = QtWidgets.QProgressBar(self.centralwidget)
        self.tempBar.setMaximumSize(QtCore.QSize(100, 20))
        self.tempBar.setStyleSheet("QProgressBar::chunk\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.0284091, x2:0, y2:0, stop:0 rgba(224, 31, 31, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"QProgressBar#progressBar\n"
"{\n"
"    height: 22px;\n"
"    text-align: center;/*文本位置*/\n"
"    font-size: 14px;\n"
"    color: black;\n"
"    border-radius: 10px;\n"
"}")
        self.tempBar.setMinimum(40)
        self.tempBar.setMaximum(80)
        self.tempBar.setProperty("value", 50)
        self.tempBar.setAlignment(QtCore.Qt.AlignCenter)
        self.tempBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.tempBar.setFormat("")
        self.tempBar.setObjectName("tempBar")
        self.horizontalLayout.addWidget(self.tempBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ipLabel.setText(_translate("MainWindow", "TextLabel"))
